sonar.host.url=https://sonar-comunity.sonar-8.geekup.io
sonar.login=58395ab76df603a811bd63def92fa79ed73831e8
sonar.projectKey=gu_skeleton_flutter
sonar.qualitygate.wait=true
sonar.projectName=gu_skeleton_flutter
sonar.projectVersion=1.0.4
sonar.sources=.
sonar.language=dart
sonar.sourceEncoding=UTF-8
sonar.issuesReport.console.enable=true
sonar.dynamicAnalysis=reuseReports
sonar.dart.analysis.useExistingOptions=true
